package com.gitlab.sszuev.textfiles.files

const val DEFAULT_BUFFER_SIZE_IN_BYTES = 8192
const val MAX_LINE_LENGTH_IN_BYTES = 8912

const val MERGE_FILES_MIN_WRITE_BUFFER_SIZE_IN_BYTES = 8192
const val MERGE_FILES_MIN_READ_BUFFER_SIZE_IN_BYTES = 1024
const val MERGE_FILES_WRITE_BUFFER_TO_TOTAL_MEMORY_ALLOCATION_RATIO = 0.9

const val LINE_READER_SINGLE_OPERATION_TIMEOUT_IN_MS = 60 * 1000L
const val LINE_READER_INTERNAL_QUEUE_SIZE = 1024

const val SORT_FILE_MIN_MEMORY_ALLOCATION_IN_BYTES = 64
const val SORT_FILE_DEFAULT_MEMORY_ALLOCATION_IN_BYTES = 8912
const val SORT_FILE_WRITE_OPERATION_TIMEOUT_IN_MS = 5 * 60 * 1000L
const val SORT_FILE_CHUNK_GAP = 0.2
const val SORT_FILE_WRITE_BUFFER_TO_TOTAL_MEMORY_ALLOCATION_RATIO = 0.9
const val SORT_FILE_NUMBER_OF_WRITE_WORKERS = 1

const val BINARY_SEARCH_MAX_NUM_OF_LINES_PER_BLOCK = 1024
const val BINARY_SEARCH_DEFAULT_BUFFER_SIZE_IN_BYTES = MAX_LINE_LENGTH_IN_BYTES * 2
